"""CUDA allocator memory debugging with Probe and Recorder workflows."""

from ._pool_identity import (
    MemoryObservationKey,
    MemoryPoolKey,
    PoolId,
    StreamId,
)
from .attribution import (
    MemoryAttributionOptions,
    MemoryAttributionStatus,
    MemoryDisplayOptions,
    MemoryEvidenceStatus,
    MemoryLifetimeOptions,
)
from .comparison import compare_phases, compare_points, compare_snapshots
from .comparison_models import (
    MatchKind,
    MemoryAllocatorScopeComparison,
    MemoryAllocatorScopePhaseDecomposition,
    MemoryLifecycleDelta,
    MemoryObservationComparison,
    MemoryPhaseComponents,
    MemoryPoolComparison,
    MemoryPoolPhaseDecomposition,
    PhaseMetric,
)
from .errors import (
    MemoryBundleError,
    MemoryDebugError,
    MemoryHistoryDisabledError,
    MemoryHistoryError,
    MemoryHistoryTruncatedError,
    MemoryReconciliationError,
    MemoryOwnershipError,
)
from .events import AllocatorEventSummary
from .lifetimes import (
    AllocationCohort,
    CohortBirth,
    CohortFreeCompletion,
    CohortFreeRequest,
    CohortPointState,
    CohortSizeBucket,
    CohortSizeOutcome,
)
from .probe import MemoryProbe
from .recording import (
    MemoryLifetimeSelection,
    MemoryObservation,
    MemoryPoint,
    MemoryRange,
    MemoryRecorder,
    MemoryRun,
)
from .reports import (
    MemoryAllocationLifetimeAnalysis,
    MemoryPhaseComparison,
    MemoryPointComparison,
    MemoryRunGroupPhaseComparison,
    MemoryRunGroupSummary,
    MemorySnapshotComparison,
    MemoryTimeline,
)
from .run_groups import (
    MemoryMetricExtrema,
    MemoryRankPhaseDecomposition,
    MemoryRankPointAggregate,
    MemoryRankPointState,
    MemoryRankPoolPhaseDecomposition,
    MemoryRunGroup,
    MemoryRunGroupPhaseAggregate,
    compare_run_group_phases,
)
from .snapshots import MemoryProbeSnapshot
from .stacks import (
    AllocationStackCoverage,
    AllocationStackDelta,
    AllocationStackSummary,
)
from .stats import AllocatorScope, MemoryStatMetric, MemoryStats, MemoryStatsDelta
from .timeline import (
    MemoryAllocatorScopeTimelineEntry,
    MemoryObservationTimelineEntry,
    MemoryPoolTimelineEntry,
)

__all__ = [
    "AllocationCohort",
    "AllocationStackCoverage",
    "AllocationStackDelta",
    "AllocationStackSummary",
    "AllocatorEventSummary",
    "AllocatorScope",
    "CohortBirth",
    "CohortFreeCompletion",
    "CohortFreeRequest",
    "CohortPointState",
    "CohortSizeBucket",
    "CohortSizeOutcome",
    "MatchKind",
    "MemoryAllocationLifetimeAnalysis",
    "MemoryAllocatorScopeComparison",
    "MemoryAllocatorScopePhaseDecomposition",
    "MemoryAllocatorScopeTimelineEntry",
    "MemoryAttributionOptions",
    "MemoryAttributionStatus",
    "MemoryBundleError",
    "MemoryDebugError",
    "MemoryDisplayOptions",
    "MemoryEvidenceStatus",
    "MemoryHistoryDisabledError",
    "MemoryHistoryError",
    "MemoryHistoryTruncatedError",
    "MemoryReconciliationError",
    "MemoryLifetimeOptions",
    "MemoryLifetimeSelection",
    "MemoryLifecycleDelta",
    "MemoryMetricExtrema",
    "MemoryObservation",
    "MemoryObservationComparison",
    "MemoryObservationKey",
    "MemoryObservationTimelineEntry",
    "MemoryOwnershipError",
    "MemoryPhaseComparison",
    "MemoryPhaseComponents",
    "MemoryPoint",
    "MemoryPointComparison",
    "MemoryPoolComparison",
    "MemoryPoolKey",
    "MemoryPoolPhaseDecomposition",
    "MemoryPoolTimelineEntry",
    "MemoryProbe",
    "MemoryProbeSnapshot",
    "MemoryRange",
    "MemoryRankPhaseDecomposition",
    "MemoryRankPointAggregate",
    "MemoryRankPointState",
    "MemoryRankPoolPhaseDecomposition",
    "MemoryRecorder",
    "MemoryRun",
    "MemoryRunGroup",
    "MemoryRunGroupPhaseAggregate",
    "MemoryRunGroupPhaseComparison",
    "MemoryRunGroupSummary",
    "MemorySnapshotComparison",
    "MemoryStatMetric",
    "MemoryStats",
    "MemoryStatsDelta",
    "MemoryTimeline",
    "PhaseMetric",
    "PoolId",
    "StreamId",
    "compare_phases",
    "compare_points",
    "compare_run_group_phases",
    "compare_snapshots",
]
